version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: plailist
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: ./server/chat
    environment:
      PLAYLISTIFY_SPOTIFY_SECRET: ${PLAYLISTIFY_SPOTIFY_SECRET}
      PLAYLISTIFY_SPOTIFY_ID: ${PLAYLISTIFY_SPOTIFY_ID}
      PLAYLISTIFY_DBHOST: postgres
      PLAYLISTIFY_DBPORT: 5432
      PLAYLISTIFY_DBUSERNAME: dev
      PLAYLISTIFY_DBPASSWORD: dev
      PLAYLISTIFY_DBNAME: plailist
      PLAYLISTIFY_SPOTIFY_REDIR: "http://127.0.0.1:8888/spotify/auth"
      PLAYLISTIFY_AUTH_REDIR: "http://127.0.0.1:5173/"
    ports:
      - "8888:8888"
      - "5173:5173"
    depends_on:
      - postgres

volumes:
  postgres-data: